In [4]:
# Question 1
import numpy as np

rand_int = np.random.randint (1, 51, size=(6, 6))
print(rand_int)

[[14  2 27 10 44 19]
 [ 2 30 15 13 47  4]
 [18 46 48 49 13  7]
 [33 38 20 40 35 39]
 [13 23 21 48 46 24]
 [44 49 24 11  4 28]]


In [6]:
# Question 2
print(f"Array Rows:\n{rand_int[:2]}")
print(f"Array Column:\n{rand_int[:, 3:]}")
even_arr = rand_int[rand_int % 2 == 0]
print(f"Print even numbers in Array:\n{even_arr}")

Array Rows:
[[14  2 27 10 44 19]
 [ 2 30 15 13 47  4]]
Array Column:
[[10 44 19]
 [13 47  4]
 [49 13  7]
 [40 35 39]
 [48 46 24]
 [11  4 28]]
Print even numbers in Array:
[14  2 10 44  2 30  4 18 46 48 38 20 40 48 46 24 44 24  4 28]


In [9]:
# Question 3
arr_reshape = rand_int.reshape(3, 2, 6)
print(f"Reshaping array:\n{arr_reshape}")

flattening = rand_int.flatten()
print(f"\nFlattened Array:\n{flattening}")

Reshaping array:
[[[14  2 27 10 44 19]
  [ 2 30 15 13 47  4]]

 [[18 46 48 49 13  7]
  [33 38 20 40 35 39]]

 [[13 23 21 48 46 24]
  [44 49 24 11  4 28]]]

Flattened Array:
[14  2 27 10 44 19  2 30 15 13 47  4 18 46 48 49 13  7 33 38 20 40 35 39
 13 23 21 48 46 24 44 49 24 11  4 28]


In [10]:
# Question 4
identity_arr = np.eye(4)
print(f"Printing Identity matrix:\n{identity_arr}")

diagonal_arr = np.diag([10, 20, 30, 40])
print(f"\nPrinting Diagonal Matrix:\n{diagonal_arr}")

Printing Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Printing Diagonal Matrix:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [11]:
# Question 5
mult_rand_arr1 = np.random.randint(1, 11, size=(4, 3))
mult_rand_arr2 = np.random.randint(1, 11, size=(3, 4))

print(f"First Operation Detail:\n{mult_rand_arr1}")
print(f"\nSecond Operation Detail:\n{mult_rand_arr2}")

result = mult_rand_arr1 @ mult_rand_arr2
print(f"\nResult of Operation of Matrix:\n{result}")

First Operation Detail:
[[10  4  7]
 [ 4  2  3]
 [ 7  6  7]
 [ 6 10  9]]

Second Operation Detail:
[[ 2  5  3  9]
 [ 5 10  1  6]
 [ 8  3  7  3]]

Result of Operation of Matrix:
[[ 96 111  83 135]
 [ 42  49  35  57]
 [100 116  76 120]
 [134 157  91 141]]


In [17]:
# Question 6
def arr_function(arr_opr):
    return np.where(arr_opr % 2 == 0, arr_opr ** 2, -1)

arr_details = np.arange(1, 7).reshape(2, 3)
print(f"Printing Array details without function:\n{arr_details}")
print(f"Printing Array after applying function:\n{arr_function(arr_details)}")

Printing Array details without function:
[[1 2 3]
 [4 5 6]]
Printing Array after applying function:
[[-1  4 -1]
 [16 -1 36]]
