In [3]:
# Q1. Create a 1D NumPy array of numbers from 10 to 50 with step size 5. Find its mean and 
# standard deviation. 
# Answer: 
import numpy as np 
arr = np.arange(10, 55, 5) 
mean_val = arr.mean() 
std_val = arr.std() 
print(arr, mean_val, std_val) 

[10 15 20 25 30 35 40 45 50] 30.0 12.909944487358056


In [19]:
# Q2. Generate a 3×3 identity matrix and multiply it with a random 3×3 matrix. 
I = np.eye(3) 
A = np.random.randint(1, 10, (3, 3)) 
result = np.dot(I, A) 
# print(result)
print(result.resize(3, 3))

None


In [5]:
# Q3. Create a 5×5 matrix with values 1 to 25, then reshape it into a 25×1 column vector. 
mat = np.arange(1, 26).reshape(5, 5) 
col_vec = mat.reshape(25, 1) 
print(col_vec)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]


In [6]:
# Q4. Simulate 1000 dice rolls and calculate the probability of getting a sum of 7. 
dice1 = np.random.randint(1, 7, 1000) 
dice2 = np.random.randint(1, 7, 1000) 
sums = dice1 + dice2 
prob_7 = np.mean(sums == 7) 
print(prob_7)

0.159


In [34]:
# Q5. Solve the system of equations: 
# 2x + y = 11 
# x − y = 1 
A = np.array([[2, 1], [1, -1]]) 
ra = np.ravel(A)
print(A)
flat = A.flatten()
print(ra)
print(flat)
print(A.reshape(-1))
A[0][0] = 3
print(flat)
print(ra)
print(A.reshape(-1))
# b = np.array([11, 1]) 
# solution = np.linalg.solve(A, b) 
# print(solution) 

[[ 2  1]
 [ 1 -1]]
[ 2  1  1 -1]
[ 2  1  1 -1]
[ 2  1  1 -1]
[ 2  1  1 -1]
[ 3  1  1 -1]
[ 3  1  1 -1]


In [8]:
# Q6. Create a 4×4 random matrix and normalize it (values between 0 and 1). 
mat = np.random.rand(4, 4) 
normalized = (mat - mat.min()) / (mat.max() - mat.min()) 
print(normalized) 

[[0.72248837 0.18518892 0.49573358 0.71233005]
 [0.96711107 0.95421706 0.         0.72804485]
 [0.07275158 0.05943846 0.97836579 0.84816834]
 [0.54792527 0.16123074 0.6301894  1.        ]]


In [25]:
# Q7. Compute the dot product and cross product of vectors [3, 4, 5] and [1, 2, 3]. 
a = np.array([3, 4, 5])
a.resize(2, 2)
print(np.max(a))
# b = np.array([1, 2, 3]) 
# dot = np.dot(a, b) 
# cross = np.cross(a, b) 
# print(dot, cross) 

5


In [38]:
a = np.array([2,3,1])
sort = a.argsort()
min = a.argmin()
max= a.argmax()
print(a)
print(sort)
print(min)
print(max)
print(a[sort])
print(a[min])
print(a[max])

[2 3 1]
[2 0 1]
2
1
[1 2 3]
1
3


In [ ]:
# Q8. Students Dataset 
# students.csv → columns: Name, Age, Gender, Score 
# Load dataset. 
# Find average score by gender. 
# Filter students scoring above 70. 
# Plot histogram of scores. 
# import pandas as pd 
# import matplotlib.pyplot as plt 
# df = pd.read_csv("students.csv") 
# print(df.groupby("Gender")["Score"].mean()) 
# print(df[df["Score"] > 70]) 
# df["Score"].hist() 
# plt.show() 

In [ ]:
# Q9. Sales Dataset 
# sales.csv → columns: Date, Product, Sales 
# Convert Date to datetime. 
# Total sales by product. 
# Find best-selling product. 
# Plot sales trend over time. 
# df = pd.read_csv("sales.csv") 
# df["Date"] = pd.to_datetime(df["Date"]) 
# print(df.groupby("Product")["Sales"].sum()) 
# print(df.groupby("Product")["Sales"].sum().idxmax()) 
# df.groupby("Date")["Sales"].sum().plot() 
# plt.show()

In [ ]:
# Q10. Employees Dataset 
# employees.csv → columns: ID, Name, Department, Salary 
# Handle missing salaries (fill with mean). 
# Find department with highest avg salary. 
# Plot salary distribution. 
# df = pd.read_csv("employees.csv") 
# df["Salary"].fillna(df["Salary"].mean(), inplace=True) 
# print(df.groupby("Department")["Salary"].mean()) 
# df["Salary"].hist() 
# plt.show() 

In [ ]:
# Q11. Movies Dataset 
# movies.csv → columns: Title, Genre, Rating 
# Count number of movies per genre. 
# Find highest-rated movie. 
# Plot bar chart of genre counts. 
# df = pd.read_csv("movies.csv") 
# print(df["Genre"].value_counts()) 
# print(df.loc[df["Rating"].idxmax()]) 
# df["Genre"].value_counts().plot(kind="bar") 
# plt.show() 

In [ ]:
# Q12. E-commerce Orders 
# orders.csv → columns: OrderID, Customer, Amount, Country 
# Total revenue by country. 
# Find top 5 customers by amount. 
# Plot revenue by country. 
# df = pd.read_csv("orders.csv") 
# print(df.groupby("Country")["Amount"].sum()) 
# print(df.groupby("Customer")["Amount"].sum().nlargest(5)) 
# df.groupby("Country")["Amount"].sum().plot(kind="bar") 
# plt.show() 

In [ ]:
# Q13. Weather Dataset 
# weather.csv → columns: Date, Temp, Rainfall 
# Find hottest day. 
# Average temperature. 
# Plot temperature trend. 
# df = pd.read_csv("weather.csv") 
# print(df.loc[df["Temp"].idxmax()]) 
# print(df["Temp"].mean()) 
# df["Temp"].plot() 
# plt.show() 

In [ ]:
# Q14. COVID-19 Cases 
# covid.csv → columns: Date, Country, Cases 
# Total cases by country. 
# Find day with highest global cases. 
# Plot top 5 countries with most cases. 
# df = pd.read_csv("covid.csv") 
# print(df.groupby("Country")["Cases"].sum()) 
# print(df.groupby("Date")["Cases"].sum().idxmax()) 
# df.groupby("Country")["Cases"].sum().nlargest(5).plot(kind="bar") 
# plt.show() 