In [3]:
import numpy as np

A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 4],
              [-2, 5]])

c = 2

d = 3

# a) compute the following: (cA), (dB) and (c+d)A
cA = c * A
dB = d * B
cd_A = (c + d) * A

print("Compute cA:\n", cA)
print("Compute dB:\n", dB)
print("Compute (c+d)A:\n", cd_A)

Compute cA:
 [[ 4 -2]
 [ 0  6]]
Compute dB:
 [[ 3 12]
 [-6 15]]
Compute (c+d)A:
 [[10 -5]
 [ 0 15]]


In [ ]:
# b) Using the results gotten, verify the scalar multiplication properties
# 1) Associativity of scalar multiplication: (c.d)A = c.(dA)
left_cd_A = (c * d) * A
right_c_dA = c * (d * A)

print("left side of associativity of scalar multiplication:\n", left_cd_A)
print("right side of associativity of scalar multiplication:\n", right_c_dA)
print("checking if associativity of scalar multiplication is True or False", np.array_equal(left_cd_A, right_c_dA))

left side of associativity of scalar multiplication:
 [[12 -6]
 [ 0 18]]
right side of associativity of scalar multiplication:
 [[12 -6]
 [ 0 18]]
checking if associativity of scalar multiplication is right: True


In [ ]:
# 2) Distributivity over matrix addition: c(A+B) = cA + cB
left_c_AB = c * (A + B)
right_cA_cB = (c * A) + (c * B)

print("left side of distributivity over matrix addition:\n", left_c_AB)
print("right side of distributivity over matrix addition:\n", right_cA_cB)
print("checking if distributivity over matrix addition is True or False:", np.array_equal(left_c_AB, right_cA_cB))

left side of distributivity over matrix addition:
 [[ 6  6]
 [-4 16]]
right side of distributivity over matrix addition:
 [[ 6  6]
 [-4 16]]
checking if distributivity over matrix addition is right: True


In [ ]:
# 3) Distributivity over scalar addition: (c+d)A = cA + dA
left_cd_A = (c + d) * A
right_cA_dA = (c * A) + (d * A)

print("left side of distributivity over scalar addition:\n", left_cd_A)
print("right side of distributivity over scalar addition:\n", right_cA_dA)
print("checking if distributivity over scalar addition is True or False:", np.array_equal(left_cd_A, right_cA_dA))

left side of distributivity over scalar addition:
 [[10 -5]
 [ 0 15]]
right side of distributivity over scalar addition:
 [[10 -5]
 [ 0 15]]
checking if distributivity over scalar addition is right: True


In [8]:
# c) Find the transpose of both matrices
print("Transpose of matrix A:\n", A.T)
print("Transpose of matrix B:\n", B.T)

Transpose of matrix A:
 [[ 2  0]
 [-1  3]]
Transpose of matrix B:
 [[ 1 -2]
 [ 4  5]]


In [ ]:
# d) Check if (A) and (B) are invertible by computing their determinants. if they are invertible, find A inverse and B inverse
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print(f"Determinant of matrix A: {det_A}")
print(f"Determinant of matrix B: {det_B}")

print("check if determinant of matrix A is not equal to zero, if True can inverse, else can not: ", np.not_equal(det_A, 0))
print("check if determinant of matrix B is not equal to zero, if True can inverse, else can not: ", np.not_equal(det_B, 0))

inverse_A = np.linalg.inv(A)
inverse_B = np.linalg.inv(B)

print("Inverse of matrix A:\n", inverse_A)
print("Inverse of matrix B:\n", inverse_B)

Determinant of matrix A: 6.0
Determinant of matrix B: 13.0
check if determinant of matrix A is equal to zero, if True can inverse:  True
check if determinant of matrix B is equal to zero, if True can inverse:  True
Inverse of matrix A:
 [[0.5        0.16666667]
 [0.         0.33333333]]
Inverse of matrix B:
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
