```
1. Create a new 5×4 matrix of scores (5 students, 4 subjects). 
Compute each student’s total score

student_score = [[65, 70, 54, 43], 
                 [87, 45, 89, 46],
                 [76, 90, 34, 56],
                 [78, 54, 76, 51],
                 [76, 34, 97, 39]]

student_score_total(student 1) = (65 + 70 + 54 + 43) = 232
student_score_total(student 1) = (65 + 70 + 54 + 43) = 267
student_score_total(student 1) = (65 + 70 + 54 + 43) = 256
student_score_total(student 1) = (65 + 70 + 54 + 43) = 259
student_score_total(student 1) = (65 + 70 + 54 + 43) = 246

students_average_subject(subject 1) = (65 + 87 + 76 + 78 + 76) / 5 = 76.4
students_average_subject(subject 2) = (70 + 45 + 90 + 54 + 34) / 5 = 58.6
students_average_subject(subject 3) = (54 + 89 + 34 + 76 + 97) / 5 = 70
students_average_subject(subject 4) = (43 + 46 + 56 + 51 + 39) / 5 = 47
```

```
2. Suppose one subject (e.g., Science) is 3 times more important than others. 
Apply scalar multiplication and recompute totals.

upgrading the last column subject by 1.5 based on result performance using scalar multiplication concept
last subject column scores = [43, 46, 56, 51, 39] * 1.5
new_last_column_score = [64, 69, 84, 76, 58]

new student score in the new upgraded subject 
student_score = [[65, 70, 54, 64], 
                 [87, 45, 89, 69],
                 [76, 90, 34, 84],
                 [78, 54, 76, 76],
                 [76, 34, 97, 58]]

new_subject_sum = [253, 290, 284, 284, 265]
```

```
3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using matrix multiplication. 

student_percentage = student_score / 100
student_score_in_percentage = [[0.65, 0.70, 0.54, 0.64], 
                               [0.87, 0.45, 0.89, 0.69],
                               [0.76, 0.90, 0.34, 0.84],
                               [0.78, 0.54, 0.76, 0.76],
                               [0.76, 0.34, 0.97, 0.58]]
```


```
4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subject?

student_score = [[65, 70, 54, 64], 
                 [87, 45, 89, 69],
                 [76, 90, 34, 84],
                 [78, 54, 76, 76],
                 [76, 34, 97, 58]]

student_three_score = [76, 90, 34, 84]
student_four_score = [78, 54, 76, 76]

adding student three  subject scores  = 76 + 90 + 34 + 84 = 284
adding student four  subject scores  = 78 + 54 + 76 + 76 = 284

since the aggregate score of student 3 and 4 are the same the both got the same mark, which means their grades are equal based on both sum and average of subject grade.


In [76]:
import numpy as np

# 1. Create a new 5×4 matrix of scores (5 students, 4 subjects). 
# Compute each student’s total score

student_score = np.array([[65, 70, 54, 43], 
                          [87, 45, 89, 46],
                          [76, 90, 34, 56],
                          [78, 54, 76, 51],
                          [76, 34, 97, 39]])

Total_score = np.sum(student_score, axis=1)
print("Total score of each student:\n")
Total_score

Total score of each student:



array([232, 267, 256, 259, 246])

In [77]:
# The average per subject. 
average_score = np.average(student_score, axis=0)
print("Average score of student:")
average_score

Average score of student:


array([76.4, 58.6, 70. , 47. ])

In [78]:
#2. Suppose one subject (e.g., Science) is 3 times more important than others. 
# Apply scalar multiplication and recompute totals.
upgrade = 1.5
science_student_score = student_score[:, 3:].copy()
new_student_score = science_student_score * upgrade
student_score[:, 3:] = new_student_score
student_score

array([[65, 70, 54, 64],
       [87, 45, 89, 69],
       [76, 90, 34, 84],
       [78, 54, 76, 76],
       [76, 34, 97, 58]])

In [79]:
# recomputing totals.
new_student_total = np.sum(student_score, axis=1)
new_student_total

array([253, 290, 284, 284, 265])

In [80]:
# 3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). 
# Compute final grades using matrix multiplication. 
percent_student_score = student_score / 100
percent_student_score

array([[0.65, 0.7 , 0.54, 0.64],
       [0.87, 0.45, 0.89, 0.69],
       [0.76, 0.9 , 0.34, 0.84],
       [0.78, 0.54, 0.76, 0.76],
       [0.76, 0.34, 0.97, 0.58]])

In [81]:
# 4. Compare Student 3 and Student 4 using vector subtraction. 
# Who performed better in each subject
up_student_3_4 = student_score[2, :] - student_score[3, :]
up_student_3_4


array([ -2,  36, -42,   8])

In [82]:
down_student_4_3 = student_score[3, :] - student_score[2, :]
down_student_4_3

array([  2, -36,  42,  -8])

In [83]:
if np.sum(up_student_3_4) == np.sum(down_student_4_3):
    print("Equal score")
elif np.sum(up_student_3_4) > np.sum(down_student_4_3):
    print("Student 3 performed better")
else:
    print("Student 3 performed better")

Equal score
